// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/Demo copy.vue')['default']
    Demo: typeof import('./src/components/DemoGood.vue['default']
    DemoBad: typeof import('./src/components/DemoBad.vue')['default']
    DemoGood: typeof import('./src/components/DemoGood.vue')['default']
  }
}
